INSERT INTO joke (id, content, author, rating) VALUES
(1, 'Why don''t scientists trust atoms? Because they make up everything!', 'John Doe', 4.5),
(2, 'Why did the scarecrow win an award? He was outstanding in his field!', 'Jane Smith', 3.8),
(3, 'Why don''t eggs tell jokes? They''d crack each other up!', 'Bob Johnson', 4.2),
(4, 'What did the ocean say to the beach? Nothing, it just waved.', 'Alice Brown', 3.6),
(5, 'Why did the math book look sad? Because it had too many problems.', 'Chris White', 4.0),
(6, 'What kind of shoes do ninjas wear? Sneakers!', 'Pat Green', 3.9),
(7, 'Why did the bicycle fall over? Because it was two-tired!', 'Sara Lee', 4.1),
(8, 'Why did the golfer bring two pairs of pants? In case he got a hole in one.', 'Mark King', 3.7),
(9, 'Why do bees have sticky hair? Because they use honeycombs.', 'Tom Grey', 4.3),
(10, 'How does a penguin build its house? Igloos it together.', 'Sam Fox', 4.2),
(11, 'Why did the coffee file a police report? It got mugged.', 'Kim Brown', 3.5),
(12, 'Why are skeletons so calm? Because nothing gets under their skin.', 'Amy Black', 3.9),
(13, 'Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels.', 'Rob Stark', 3.6),
(14, 'How does NASA organize a party? They planet.', 'Sue White', 4.4),
(15, 'What do you call fake spaghetti? An impasta!', 'Jerry Clark', 3.8),
(16, 'Why did the tomato turn red? Because it saw the salad dressing!', 'Paul Bright', 4.0),
(17, 'Why can’t you give Elsa a balloon? Because she will let it go.', 'Lisa Snow', 3.7),
(18, 'Why did the kid bring a ladder to school? Because he wanted to go to high school.', 'Megan Sky', 3.9),
(19, 'How do you make a tissue dance? Put a little boogie in it!', 'Jim Quick', 4.2),
(20, 'Why don’t skeletons fight each other? They don’t have the guts.', 'Beth Flash', 4.1),
(21, 'What did one plate say to another? Tonight, dinner’s on me.', 'Tom Plate', 3.6),
(22, 'Why did the golfer bring extra socks? In case he got a hole in one.', 'Nina Green', 4.3),
(23, 'How does a train eat? It goes chew chew!', 'Gregg Steam', 3.8),
(24, 'Why was the math book sad? It had too many problems.', 'Alex Chalk', 3.9),
(25, 'What did the big flower say to the little flower? Hey, bud!', 'Clara Fields', 4.0),
(26, 'How does a cucumber become a pickle? It goes through a jarring experience.', 'Peter Vine', 3.5),
(27, 'What kind of tree fits in your hand? A palm tree!', 'Will Bark', 4.1),
(28, 'Why did the student eat his homework? The teacher said it was a piece of cake.', 'Danny Learn', 4.4),
(29, 'What did the zero say to the eight? Nice belt!', 'Jill Rounds', 3.7),
(30, 'Why don’t some fish play piano? Because they’re afraid of the scales.', 'Pat Scales', 3.9),
(31, 'What’s orange and sounds like a parrot? A carrot.', 'Mike Root', 3.6),
(32, 'What did the left eye say to the right eye? Between you and me, something smells.', 'Fay Eye', 4.1),
(33, 'Why did Cinderella get kicked off the soccer team? Because she ran away from the ball.', 'Ella Shoe', 4.2),
(34, 'What do you call cheese that isn’t yours? Nacho cheese.', 'Carlos Chip', 4.0),
(35, 'Why are elevator jokes so good? They work on many levels.', 'Lisa Lift', 3.9),
(36, 'How did the barber win the race? He knew all the shortcuts.', 'Hairy Combs', 4.1),
(37, 'Why did the music teacher go to jail? Because she got caught with a whole note.', 'Mel Odie', 4.3),
(38, 'What do you get when you cross a snowman with a vampire? Frostbite.', 'Coldy Bite', 4.2),
(39, 'Why did the nurse need a red pen at work? In case she needed to draw blood.', 'Pat Blood', 3.5),
(40, 'Why don’t you write with a broken pencil? Because it’s pointless.', 'Tim Graph', 4.0),
(41, 'What did the grape do when he got stepped on? Nothing but let out a little wine.', 'Paul Vine', 4.1),
(42, 'Why did the cookie go to the hospital? Because it felt crumby.', 'Chip Sugar', 4.2),
(43, 'How does a snowman get around? By riding an “icicle”!', 'Frosty Ride', 3.8),
(44, 'What lights up a soccer stadium? A soccer match.', 'Daisy Field', 3.9),
(45, 'Why don’t we tell secrets on a farm? Because the potatoes have eyes and the corn has ears.', 'Sam Root', 4.0),
(46, 'Why did the cat sit on the computer? To keep an eye on the mouse.', 'Kitty Paw', 3.6),
(47, 'What did the traffic light say to the car? Don’t look, I’m changing.', 'Blinky Road', 3.7),
(48, 'What kind of jokes are allowed during quarantine? Inside jokes.', 'Liv Room', 4.3),
(49, 'Why did the frog take the bus to work today? His car got toad away.', 'Ribby Hop', 3.9),
(50, 'Why don’t eggs play sports? Because they’d crack up.', 'Shell Yolk', 4.0);

